### ISSUE TITLE
cannot compile ruby-lorcon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Detry322/lorcon#2]
```
What steps will reproduce the problem?
jwest@TestBox:~/lorcon/ruby-lorcon$ make

What is the expected output? What do you see instead?
gcc -I. -I. -I/usr/lib/ruby/1.8/i486-linux -I. -D_FILE_OFFSET_BITS=64  -fPIC 
-fno-strict-aliasing -g -g -O2  -fPIC   -c Lorcon2.c
In file included from Lorcon2.h:10,
                 from Lorcon2.c:1:
/usr/local/include/lorcon2/lorcon.h:29:27: error: lorcon_packet.h: No such file 
or directory
In file included from Lorcon2.h:10,
                 from Lorcon2.c:1:
/usr/local/include/lorcon2/lorcon.h:42: error: expected declaration specifiers 
or ‘...’ before ‘lorcon_packet_t’
/usr/local/include/lorcon2/lorcon.h:113: error: expected declaration specifiers 
or ‘...’ before ‘lorcon_packet_t’
/usr/local/include/lorcon2/lorcon.h:124: error: expected declaration specifiers 
or ‘...’ before ‘lorcon_packet_t’
Lorcon2.c: In function ‘Lorcon_inject_packet’:
Lorcon2.c:471: error: too many arguments to function ‘lorcon_inject’
Lorcon2.c:474: error: too many arguments to function ‘lorcon_inject’
Lorcon2.c: In function ‘Lorcon_capture_loop’:
Lorcon2.c:533: error: too many arguments to function ‘lorcon_next_ex’
make: *** [Lorcon2.o] Error 1

What version of the product are you using? On what operating system?
edge, attempting to compile on Linux TestBox 2.6.32-40-generic #87-Ubuntu SMP 
Mon Mar 5 20:26:31 UTC 2012 i686 GNU/Linux (Ubuntu 10.04)

Please provide any additional information below.

```

Original issue reported on code.google.com by `jw...@suretec.co` on 25 Apr 2012 at 4:52

**Comment by GoogleCodeExporter** [comment]
```
Hey if your still having this issue

Try adding --with-name-include="/usr/include/lorcon2/" 

this is because lorcon by default installs the header files to 
/usr/local/include/lorcon2 and your system is expecting them in 
/usr/include/lorcon2
```

Original comment by `TheX...@gmail.com` on 21 Sep 2012 at 2:17

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Files have been patched and it should now compile and run on 1.8 and 1.9
```

Original comment by `TheX...@gmail.com` on 20 Nov 2012 at 3:56
- Changed state: **Fixed**
